<?php
	$pageTitle = "Historia de Sahuayo.";
	$pageDescription = "";
	$pageKeywords = "";
	$ogTitle = "";
	$ogImage = "";
	$ogUrl = "";
	$ogSiteName = "";
	$ogDescription = "";
	require_once 'header.php';
?>
		<div class="gtco-section">
			<div class="gtco-container">
				<main>
					<h1><?php echo $pageTitle ?></h1>

					<p>El municipio de Sahuayo de Morelos, ubicado en el centro-occidente del estado de Michoacán de Ocampo, México, representa un punto de confluencia histórica y cultural de gran relevancia. Reconocida por su dinamismo regional, la ciudad de Sahuayo de Morelos es la cabecera municipal y se posiciona como la sexta ciudad más poblada de Michoacán y la segunda en importancia dentro de la Región Lerma-Chapala, solo superada por Zamora de Hidalgo.</p>

					<h2>Contexto geográfico y demográfico.</h2>

					<p>Geográficamente, Sahuayo se asienta en una zona de transición que abarca la depresión Lerma-Chapala, el sistema volcánico transversal y elevaciones como los cerros de Las Gallinas, Santiago y La Caja. Esta configuración topográfica, junto con un clima templado caracterizado por lluvias en verano, una precipitación pluvial anual de 709.0 milímetros y temperaturas que oscilan entre 10.4 y 26.0°C, ha sido fundamental para su desarrollo. Los suelos predominantes son chernozem, formados a lo largo de millones de años y aptos principalmente para la ganadería y, en menor medida, para la agricultura. La presencia de la depresión Lerma-Chapala, una cuenca fértil y propicia para la acumulación de agua, explica la vocación agrícola y ganadera que ha definido la economía local a lo largo de su historia. La disponibilidad de agua y tierras cultivables ha sido un factor determinante para el establecimiento y sostenimiento de asentamientos humanos duraderos. En cuanto a su ecosistema, dominan las praderas con mezquite, linaloe y nopal, mientras que su fauna incluye armadillos, conejos, coyotes y ardillas. Demográficamente, la cabecera municipal de Sahuayo de Morelos contaba con aproximadamente 78,477 habitantes en 2020, siendo un centro vital para el comercio y la industria en la región.</p>

					<h2>Etimología del nombre "Sahuayo" y sus interpretaciones.</h2>

					<p>El nombre "Sahuayo" posee un origen náhuatl, y su etimología ha sido objeto de diversas interpretaciones. Una de ellas, propuesta por el filólogo y licenciado Cecilio A. Róbelo, sugiere que significa "en donde da la sarna", derivado de las palabras náhuatl <i>zahuatl</i> ('sarna, roña, tiña') y el sufijo <i>-yo</i> ('que tiene'). Sin embargo, otra interpretación, atribuida al Dr. Antonio Peñafiel, desglosa el término en <i>tzacuatl</i> ('vasija' o 'pot') y <i>ayotl</i> ('tortuga'), resultando en "vasija con forma de tortuga". Esta segunda interpretación es la que se ha incorporado al simbolismo local, evidenciado en el escudo municipal de Sahuayo, que presenta una tortuga sobre una piedra, representando la fundación de la localidad en 1530. La adopción de esta etimología en la iconografía oficial no es casual; refleja una elección cultural consciente por parte de la comunidad para construir una narrativa de origen que sea más simbólica y positiva. La preferencia por la "vasija con forma de tortuga" sobre la referencia a la sarna ilustra cómo las comunidades seleccionan y refuerzan ciertos significados toponímicos para moldear su auto-percepción y su historia cívica, optando por una identidad arraigada en elementos naturales o culturales que resuenan de manera más favorable.</p>

					<hr>

					<h2>Época Prehispánica: Asentamientos originales y dinámicas regionales.</h2>

					<p>La historia de Sahuayo de Morelos se remonta a un complejo panorama prehispánico, marcado por la interacción de diversas culturas indígenas en la región.</p>

					<h3>Los Primeros pobladores de la región y su relación con el lago de Chapala.</h3>

					<p>Se considera que los primeros habitantes de la región de Sahuayo, al igual que muchas otras localidades a orillas del Lago de Chapala, eran de origen azteca. La tradición oral sugiere que durante la peregrinación de esta etnia desde Aztlán hacia los grandes valles, se dividieron en varias facciones, y en los lugares donde se asentaron, fundaron pueblos con nombres derivados de su propia lengua, como fue el caso de Sahuayo. No obstante, la región del Lago de Chapala también fue habitada por el pueblo Coca, un grupo étnico indígena que se extendía por los valles salitrales de Chapala, especialmente en Mezcala y otras comunidades cercanas en el estado de Jalisco. Los Cocas conformaron tres <i>tlatoanazgos</i> (señoríos): Chapallan, Coinan y el Reino de Cocula, de donde tomaron su nombre. La presencia de objetos de cerámica Coca en el Lago de Chapala confirma su arraigo en la zona. El Lago de Chapala, un cuerpo de agua dulce de gran extensión, se ubica entre los estados de Jalisco y Michoacán, con municipios michoacanos como Cojumatlán de Régules, Venustiano Carranza y Briseñas en sus límites. Esta diversidad de grupos indígenas en la cuenca del lago indica que la región de Sahuayo no estuvo bajo el control monolítico de una única cultura, sino que fue un punto de encuentro y posible frontera entre diferentes influencias étnicas, con la presencia temprana de poblaciones de origen azteca y la consolidada presencia de los Cocas.</p>

					<h3>La hegemonía Purépecha en Michoacán y su interacción con otros grupos (Nahuas, Coca, Mexicas).</h3>

					<p>A pesar de la posible presencia azteca temprana, gran parte del territorio michoacano, incluyendo la región de Sahuayo, estuvo bajo la influencia y posterior dominio de la cultura Purépecha. Los Purépechas, que llegaron del norte en el siglo IX y establecieron su capital en Pátzcuaro, se consolidaron como una cultura dominante, imponiendo su hegemonía económica, religiosa, militar y cultural sobre otros grupos que también habitaban la región, como los Nahuas, Otomíes, Matlatzincas (o Pirindas) y Tecos. En el siglo XIV, el <i>irecha</i> (gobernante) Tariácuri, conocido como "Sacerdote del Viento", unificó y expandió el imperio, dividiendo sus dominios en tres señoríos principales: Pátzcuaro, Ihuatzio y Tzintzuntzan.</p>

					<p>La capacidad de los Purépechas para mantener esta hegemonía y, de manera crucial, para repeler y derrotar en múltiples ocasiones a los poderosos Mexicas (Aztecas), como lo hizo Tzitzispandácuare al mando de Axayácatl , demuestra una organización estatal y militar superior. Su éxito militar se debió en parte a su avanzada habilidad en el trabajo del cobre y el oro, lo que les otorgó una ventaja tecnológica singular en Mesoamérica y los convirtió en una potencia regional capaz de resistir el expansionismo azteca. La lengua purépecha, sin relación con otros idiomas de la región pero con similitudes al quechua de los Incas, sugiere orígenes y patrones migratorios únicos que contribuyeron a su identidad distintiva y resiliencia cultural. Los Purépechas eran politeístas, con Tiripeme Curicaueri ("Precioso que es Fuego") como su deidad principal. Este dominio purépecha sobre un mosaico de grupos indígenas en Michoacán, incluyendo la eventual sumisión de la región de Sahuayo, configura un paisaje prehispánico complejo y dinámico, lejos de una homogeneidad cultural.</p>

					<h3>El Papel de Tzitzispandácuare y la expansión purépecha.</h3>

					<p>A mediados del siglo XV, el imperio Purépecha consolidó su poder bajo el liderazgo de Tzitzispandácuare, señor de Tzintzuntzan e hijo de Tangáxoan. Este <i>cazonci</i> es recordado por su victoria decisiva sobre los Mexicas, dirigidos por Axayácatl, tras la destrucción de Taximaroa. Su sucesor, Zuangua, continuó impulsando las conquistas del imperio. Fue durante este período de fuerte predominio purépecha que la región de Sahuayo fue sometida al imperio Tarasco (Purépecha). Esta integración de Sahuayo en la esfera de influencia purépecha, a pesar de sus posibles lazos tempranos con poblaciones de origen azteca, ilustra la fluidez de las fronteras territoriales prehispánicas y la capacidad de los Purépechas para incorporar y controlar vastas áreas de Michoacán. La expansión purépecha no solo fue territorial, sino que implicó la imposición de su sistema político y cultural sobre las poblaciones locales, un proceso de integración que definió la estructura de poder en la región antes de la llegada de los españoles.</p>

					<hr>

					<h2>La conquista y el establecimiento colonial (Siglos XVI-XVIII).</h2>

					<p>La llegada de los conquistadores españoles a Michoacán marcó un punto de inflexión radical en la historia de Sahuayo, transformando sus estructuras políticas, sociales, económicas y religiosas.</p>

					<h3>La llegada española: Nuño Beltrán de Guzmán y el sistema de encomiendas.</h3>

					<p>Tras la conquista, la región de Sahuayo fue integrada al sistema colonial español, pasando a formar parte de la encomienda de Hernán Cortés, quien posteriormente la cedió a Gonzalo de Galván. Este sistema, que otorgaba a los conquistadores el derecho a recibir tributos y servicios de las poblaciones indígenas a cambio de su "protección" y evangelización, fue una de las primeras formas de explotación colonial. Hernán Cortés ya había concedido encomiendas desde septiembre de 1522.</p>

					<p>Un actor clave en la brutalidad de la conquista en el occidente de México fue Nuño Beltrán de Guzmán. Este conquistador, conocido por su crueldad y excesos, llegó al nuevo mundo en 1526 y fue nombrado gobernador de Pánuco. Posteriormente, asumió la presidencia de la real audiencia de Nueva España, pero su conducta despótica y el abuso hacia las poblaciones indígenas le valieron la excomunión y la pérdida de su cargo. Entre 1529 y 1530, Guzmán arremetió contra el imperio Purépecha. A pesar de haber sido recibido pacíficamente por el <i>cazonci</i> Tangáxoan Tzíntzicha, quien le ofreció regalos de oro y plata, Guzmán respondió torturando y ejecutando al monarca. Sus fuerzas saquearon la otrora poderosa nación Purépecha, provocando la muerte o huida de gran parte de la población a las montañas. La violencia de esta imposición se refleja incluso en el escudo municipal de Sahuayo, que representa una serpiente emplumada (Quetzalcóatl) luchando contra la cruz, simbolizando la conquista de Sahuayo por Nuño Beltrán de Guzmán. La rápida integración de Sahuayo en el sistema de encomiendas y las acciones de figuras como Guzmán ilustran la naturaleza violenta y extractiva de la conquista española, que desmanteló las estructuras políticas y sociales indígenas para establecer un nuevo orden basado en la explotación.</p>

					<h3>La evangelización franciscana y la figura de Fray Juan de Badia.</h3>

					<p>Paralelamente a la conquista militar y administrativa, se llevó a cabo la "conquista espiritual", un proceso fundamental para la consolidación del dominio español. En la región de Sahuayo, esta labor fue encomendada a los frailes de la orden de San Francisco, atribuyéndose específicamente a Fray Juan de Badia. Los misioneros franciscanos llegaron a Michoacán en 1525 y, con el apoyo inicial del <i>cazonci</i>, comenzaron a instruir a la población en la nueva fe. Fray Martín de Jesús de la Coruña es reconocido como el primer apóstol de Michoacán por su labor evangelizadora.</p>

					<p>Aunque otras órdenes mendicantes como los Agustinos y, posteriormente, los Jesuitas, también establecieron misiones en Michoacán, los Franciscanos fueron los pioneros en esta región. Su estrategia no se limitó a la conversión religiosa; implicó una reorganización social profunda. Los misioneros fundaron "barrios de indios" en las localidades más pobladas, donde asignaban terrenos y establecían instituciones como Hospitales de Indios (conocidos como Huatáperas en purépecha), escuelas y capillas. Esta dualidad de la conquista espiritual, que combinaba la imposición ideológica con la provisión de ciertos servicios y la reorganización social, buscaba integrar a las poblaciones indígenas en el sistema colonial. Si bien la evangelización ofrecía un nuevo marco de creencias y, en algunos casos, una forma de protección, también implicaba la asimilación cultural y la subordinación a la autoridad eclesiástica y civil española, consolidando así el control sobre la población.</p>

					<h3>Evolución de la dependencia eclesiástica y civil de Sahuayo.</h3>

					<p>La integración de Sahuayo en la administración colonial fue un proceso dinámico y cambiante. Para 1540, Sahuayo dependía eclesiásticamente de Jiquilpan. Quince años después, en 1555, la localidad pasó a pertenecer a Jacona. Finalmente, en 1570, con la secularización de Ixtlán como parroquia, Sahuayo se integró a ella, junto con Caro, Guarachita y Cojumatlán, y su dependencia civil recayó en Zamora. Estas sucesivas redefiniciones de las jurisdicciones eclesiásticas y civiles ilustran los esfuerzos de la Corona española por consolidar su control y establecer una administración efectiva en los vastos territorios de la Nueva España. Cada cambio reflejaba la adaptación a las realidades demográficas, económicas y de poblamiento, así como la búsqueda de una mayor eficiencia en la recaudación de tributos y la gestión de la población. La transición de una encomienda inicial a dependencias parroquiales y civiles más formalizadas demuestra la gradual construcción del estado colonial y la inserción de Sahuayo en redes administrativas y religiosas más amplias.</p>

					<h3>Transformación agraria: El surgimiento de estancias ganaderas y el despojo de tierras indígenas.</h3>

					<p>A partir de 1545, la expansión española en la región de Sahuayo se acentuó, lo que llevó a un sistemático despojo de las tierras de las comunidades indígenas. Este proceso se intensificó con la introducción de la ganadería, que se convirtió en un instrumento clave para la privatización de las antiguas tierras indígenas durante el período colonial en México. En 1567, el Marqués de Falces ya había distribuido la región de Sahuayo para el establecimiento de <i>estancias ganaderas</i> españolas.</p>

					<p>La proliferación del ganado (vacuno, caballar, ovino, caprino y porcino) transformó drásticamente el paisaje y el uso del suelo. El concepto español de "pastos comunes" colisionó con las prácticas agrícolas indígenas, generando "amargas quejas" por la invasión y destrucción de sus cultivos por parte del ganado errante. Para controlar este fenómeno y consolidar la propiedad española, el gobierno virreinal comenzó a otorgar <i>mercedes de sitios de ganado</i> a partir de 1540, lo que implicaba la posesión legal de la tierra. Los españoles se valieron de diversas estrategias, como la compra, el arrendamiento y, predominantemente, el despojo, para adueñarse progresivamente de las tierras y establecer su dominio sobre la región. La ganadería, por lo tanto, no fue solo una actividad económica, sino un motor fundamental para la reestructuración de la tenencia de la tierra, la creación de grandes propiedades y la marginación de las comunidades indígenas, sentando las bases para conflictos agrarios que perdurarían por siglos.</p>

					<h3>El caso de la hacienda de Guaracha: Formación, consolidación y su impacto socioeconómico.</h3>

					<p>La hacienda de Guaracha representa un caso paradigmático de la transformación agraria colonial en el occidente de Michoacán. Legalmente establecida en 1643 por Pedro de Salada (o Saldaña) de Zamora, quien formalizó sus despojos de tierras , Guaracha se convirtió en el latifundio más extenso de la región. Su vasto territorio abarcaba localidades como Copándaro, Cuztla, La Palma, Cojumatlán, Chavinda y Buenavista. La formación de esta hacienda se logró mediante una combinación de despojo, compraventas ilegales de tierras indígenas y la absorción de comunidades, lo que les permitía asegurar una fuerza de trabajo.</p>

					<p>La disminución drástica de la población indígena debido a las epidemias durante el período colonial obligó a la hacienda a introducir esclavos africanos, lo que a su vez contribuyó a la formación de nuevas castas en la región. A principios del siglo XVIII, un cambio en la propiedad y administración de la hacienda inauguró un "período de terror" que se mantuvo hasta su disolución. La principal actividad productiva de Guaracha a finales del siglo XIX era el cultivo de caña para la elaboración de azúcar y alcohol, aunque también se cultivaban trigo, maíz, garbanzo y camote, y se practicaba la ganadería. La hacienda de Guaracha es un claro ejemplo de cómo las fuerzas económicas coloniales impulsaron la concentración de tierras y la explotación de mano de obra, reconfigurando profundamente el tejido demográfico y social de la región y perpetuando un sistema de profundas desigualdades y control.</p>

					<h3>Crisis demográficas: El impacto de epidemias y conflictos en la población local.</h3>

					<p>Las poblaciones de Michoacán, incluyendo la región de Sahuayo, sufrieron severas crisis demográficas a lo largo del período colonial, principalmente debido a epidemias y hambrunas. Durante la época de la conquista, la población purépecha fue diezmada por enfermedades como la viruela, causando la muerte de miles de habitantes en lugares como Tzintzuntzan. Esta catástrofe demográfica generó una escasez de mano de obra que, como se mencionó, llevó a la introducción de esclavos africanos en las haciendas como Guaracha , alterando fundamentalmente la composición étnica y social de la región.</p>

					<p>Posteriormente, en la segunda mitad del siglo XVIII, Michoacán experimentó importantes crisis de mortalidad, especialmente entre 1785 y 1786. Estas crisis fueron resultado de la combinación de hambrunas por la pérdida de cosechas y la propagación de diversas epidemias, comúnmente identificadas como fiebres, aunque la viruela de 1780 fue particularmente devastadora. La llegada de migrantes desde El Bajío, huyendo de condiciones similares, probablemente contribuyó a la diseminación de estas enfermedades en Michoacán. El impacto de estas crisis se tradujo en una contracción general de la población y una aceleración del proceso de <i>mestizaje</i> en parroquias como Taximaroa. La recurrencia de estas catástrofes demográficas subraya la vulnerabilidad de las poblaciones indígenas y mestizas ante las enfermedades y la escasez de alimentos, y cómo estos factores no solo redujeron la población, sino que también impulsaron cambios sociales profundos, como la mezcla racial y la reconfiguración de las estructuras comunitarias.</p>

					<hr>

					<h2>Sahuayo en el México independiente (Siglo XIX).</h2>

					<p>El siglo XIX fue un período de profundas transformaciones para México, y Sahuayo no fue ajeno a los movimientos que llevaron a la independencia y a la consolidación de la nación.</p>

					<h3>Participación en la guerra de independencia: Figuras locales y la resistencia en Mezcala.</h3>

					<p>Aunque Sahuayo no figura como un campo de batalla principal en los registros de la Guerra de Independencia, su contribución al movimiento se manifiesta a través de figuras locales prominentes y su conexión con focos de resistencia regional. Un ejemplo notable es Marcos Castellanos Mendoza (1747-1826), un presbítero insurgente nacido en La Palma, entonces parte del territorio sahuayense, y bautizado en la Parroquia de Santiago Apóstol de Sahuayo. Castellanos, quien ejerció como cura en Sahuayo entre 1789 y 1799, había estudiado en el Seminario de Valladolid, donde conoció a Miguel Hidalgo y Costilla y a José María Morelos y Pavón, futuros líderes insurgentes. Su papel como héroe de la Guerra de Independencia en la Ciénega de Chapala es reconocido, al punto de que un municipio lleva su nombre.</p>

					<p>La resistencia en la Isla de Mezcala, un bastión insurgente en el Lago de Chapala, fue un episodio crucial de la guerra en la región. Entre 1812 y 1816, esta isla fue escenario de constantes batallas entre insurgentes indígenas, liderados por figuras como Encarnación Rosas y el propio Marcos Castellanos, y las fuerzas realistas, quienes nunca lograron someterlos. Además, José Antonio Torres, conocido como "El Amo Torres", lideró a un grupo de insurgentes indígenas que recorrieron Sahuayo, Tizapán el Alto, Atoyac y Zacoalco de Torres, logrando la primera victoria insurgente en Jalisco en Zacoalco el 4 de noviembre de 1810 y tomando Guadalajara. Estos eventos demuestran que, si bien Sahuayo no fue un epicentro militar directo, sus habitantes y su territorio estuvieron intrínsecamente ligados a la lucha, ya sea a través de líderes locales que se unieron a la causa o por ser parte de las rutas y áreas de influencia de los movimientos insurgentes. La hacienda de Guaracha, una entidad económica dominante en la región, apoyó activamente a la facción realista y, como consecuencia, sufrió múltiples asaltos por parte de los insurgentes. Esto indica que el conflicto por la independencia permeó las estructuras sociales y económicas locales, reflejando las divisiones y lealtades de la época.</p>

					<h3>La constitución de Sahuayo como municipio (1831).</h3>

					<p>Un hito fundamental en la historia cívica de Sahuayo fue su constitución como municipio el 10 de diciembre de 1831, mediante una ley específica. Este acto representa una consecuencia directa de la reorganización administrativa que siguió a la consumación de la Independencia de México. La transición de una dependencia colonial (primero de Jiquilpan, luego de Jacona y finalmente de Ixtlán y Zamora) a una entidad municipal autónoma significó un paso crucial en la formación del nuevo Estado mexicano y la descentralización del poder. La creación del municipio de Sahuayo marcó el inicio de una nueva era de autonomía local y la consolidación de su identidad cívica, liberándose de las estructuras administrativas coloniales y asumiendo un papel más activo en su propio gobierno y desarrollo.</p>

					<h3>La hacienda de Guaracha durante el Siglo XIX: Cambios de propiedad y su relevancia.</h3>

					<p>A lo largo del siglo XIX, la hacienda de Guaracha, un pilar económico de la región, experimentó cambios significativos en su propiedad. En 1790, la hacienda fue adquirida en subasta por Victorino Jasso Dávalos. Sin embargo, un evento de gran trascendencia ocurrió en 1861, en pleno período de la Reforma en México: la mitad de la hacienda de Guaracha fue vendida por su propietaria, Doña Antonia Moreno de Depayre, a más de 50 compradores. La porción vendida abarcaba la parte occidental de la Laguna y Cojumatlán, lo que propició la emergencia de nuevos propietarios adinerados. En 1837, la hacienda había sido valuada en 55,000 pesos, y finalmente, Don Tirso Arregui la vendió fragmentada por 110,000 pesos.</p>

					<p>Esta fragmentación y venta de una porción tan significativa de la hacienda de Guaracha en 1861, después de haber sido un latifundio masivo por siglos, refleja las profundas transformaciones en los patrones de tenencia de la tierra durante el siglo XIX. Aunque la venta fue realizada por una propietaria privada, el contexto de las leyes de Reforma, que buscaban desamortizar propiedades corporativas y promover la propiedad privada, pudo haber influido en la dinámica de estas transacciones. La venta a múltiples compradores, aunque no constituyó una reforma agraria en el sentido de redistribución a campesinos sin tierra, sí implicó una reestructuración de la élite terrateniente y la aparición de nuevos actores económicos en la región. Este evento ilustra cómo las políticas nacionales y los cambios socioeconómicos más amplios impactaron directamente las estructuras de propiedad local, marcando una evolución en la concentración de la riqueza y el poder en Sahuayo.</p>

					<h3>Repercusiones de la reforma en la región.</h3>

					<p>El período de la Reforma en México (mediados del siglo XIX) fue una época de intensos conflictos entre liberales y conservadores, que buscaban redefinir la estructura política y social del país. Si bien la información específica sobre la participación directa de Sahuayo en los conflictos armados de la Reforma es limitada en los datos disponibles, la venta de la mitad de la hacienda de Guaracha en 1861 se inscribe cronológicamente en este período de profundas reformas liberales. Las leyes de Reforma, que buscaban desamortizar bienes de corporaciones civiles y eclesiásticas y promover la propiedad individual, generaron un clima de inestabilidad y redefinición de la tenencia de la tierra en todo el país. Aunque la venta de Guaracha fue una transacción privada, el contexto de la Reforma, que desafiaba las estructuras de poder tradicionales y fomentaba la liberalización económica, probablemente facilitó este tipo de transacciones a gran escala. La Iglesia, por ejemplo, se puso en guardia contra el liberalismo y sus reformas que abolían ciertos privilegios eclesiásticos. Esto sugiere que Sahuayo, al igual que otras regiones, experimentó los efectos indirectos de estas políticas nacionales, que aceleraron los cambios en la propiedad de la tierra y la reconfiguración de las jerarquías sociales, incluso sin una participación directa en los combates más conocidos.</p>

					<hr>

					<h2>El siglo XX: Modernización, conflictos sociales y desarrollo urbano.</h2>

					<p>El siglo XX trajo consigo una serie de transformaciones fundamentales para Sahuayo, marcadas por la modernización, los conflictos sociales derivados de la Revolución y la Guerra Cristera, y un notable desarrollo urbano.</p>

					<h3>El Porfiriato: Infraestructura (Ferrocarril) y las crecientes desigualdades.</h3>

					<p>El Porfiriato (1876-1911) fue una era de modernización y desarrollo de infraestructura en México, y Sahuayo se integró a esta dinámica con la llegada del ferrocarril a la hacienda de la Guaracha en 1901. La construcción de vías férreas buscaba impulsar el desarrollo económico y facilitar el transporte de productos. Sin embargo, esta modernización se produjo en un contexto de profundas desigualdades económicas y sociales. A pesar de la "paz porfiriana" y la erradicación del bandidaje, la mayoría de la población enfrentaba pobreza, falta de empleo y un aumento en los precios de los productos básicos. Las rutas comerciales de Michoacán durante este período reflejaban una significativa actividad de intercambio tanto dentro del estado como con otras entidades. La llegada del ferrocarril, si bien representó un avance tecnológico, benefició principalmente a los grandes terratenientes y a las élites económicas, exacerbando las disparidades sociales. Este contraste entre el progreso de la infraestructura y el deterioro de las condiciones de vida de la mayoría sentó las bases para el descontento social que culminaría en la Revolución Mexicana.</p>

					<h3>La desecación del Lago de Chapala: Causas y consecuencias para Sahuayo.</h3>

					<p>Una de las transformaciones ambientales con mayores repercusiones para la región de Sahuayo fue el inicio de la desecación del Lago de Chapala en 1905. Esta iniciativa, impulsada por intereses que consideraban los humedales como "terreno desperdiciado" que podía convertirse en tierras cultivables , tuvo profundas implicaciones socioeconómicas. La desecación incrementó la riqueza de los terratenientes locales, quienes obtuvieron más tierras y utilizaron su control sobre el agua para despojar o dominar a los campesinos. Este proceso de modificación ambiental, disfrazado de "progreso", se convirtió en un poderoso mecanismo para acentuar las desigualdades existentes, concentrar la riqueza y agudizar los conflictos por la tierra y el agua. La cuenca Lerma-Chapala, de la que forma parte Sahuayo, ha sufrido además altos niveles de contaminación debido a descargas industriales, actividades agropecuarias y la falta de plantas de tratamiento de aguas residuales. La desecación y la incorporación de los humedales a la agricultura capitalista, junto con la construcción de presas y la deforestación, han impactado negativamente el ecosistema del lago y los medios de vida tradicionales, llevando a la desaparición o reducción de especies endémicas. Esta transformación ambiental, motivada por intereses económicos particulares, no solo alteró el paisaje natural de la región, sino que también exacerbó las tensiones sociales y agrarias, preparando el terreno para las demandas revolucionarias.</p>

					<h3>La revolución Mexicana y la reforma agraria: El ejido Emiliano Zapata.</h3>

					<p>La participación de Sahuayo en la Revolución Mexicana fue inicialmente limitada y tardía. En 1912, la ruptura de una presa que había desecado la región afectó a la población, lo que, junto con otros desastres naturales, impidió una participación inmediata en el movimiento revolucionario. No fue sino hasta 1916 y 1920 que la población de Sahuayo se involucró activamente en la Revolución. Tras la resolución del conflicto Cristero (post-1929), la campaña anti-agrarista liderada por el cura local intimidó a los campesinos que intentaban recuperar sus tierras.</p>

					<p>Sin embargo, la verdadera transformación agraria llegó con la intervención del general Lázaro Cárdenas. En 1930, siendo gobernador de Michoacán, Cárdenas emitió una resolución para distribuir parte de las tierras de la hacienda de Guaracha entre los campesinos de Sahuayo. Posteriormente, en 1936, ya como presidente de la república, Cárdenas ordenó el reparto definitivo de las tierras de la hacienda, lo que culminó con la fundación del ejido Emiliano Zapata. La hacienda de La Guaracha, que había sido el latifundio más grande del occidente de Michoacán, fue convertida en un "ejido modelo", marcando la "fase radical" de la reforma agraria cardenista. Esta transición de un sistema de grandes propiedades a la tenencia comunal de la tierra representó una reestructuración fundamental del poder económico y de las relaciones sociales, buscando corregir las injusticias históricas del despojo agrario y empoderar a la población campesina.</p>

					<h3>La Guerra Cristera: Causas, desarrollo y el martirio de José Sánchez del Río.</h3>

					<p>La Guerra Cristera (1926-1929) fue un conflicto armado de gran envergadura en México, provocado principalmente por el rechazo a las políticas anticlericales del gobierno, en particular la Ley Calles, que buscaba limitar la influencia de la Iglesia Católica. El conflicto concluyó en 1929 con un acuerdo que promovió la coexistencia entre la Iglesia y el Estado. Michoacán fue uno de los estados donde la resistencia Cristera fue más encarnizada, con el distrito de Coalcomán llegando a autoproclamarse una "zona libre" autónoma.</p>

					<p>Sahuayo jugó un papel significativo en este conflicto, destacándose por el martirio de José Sánchez del Río. Nacido en Sahuayo el 28 de marzo de 1913, José fue un adolescente cristero de 14 años que fue procesado, torturado y ejecutado en su ciudad natal el 10 de febrero de 1928. Fue encarcelado en la parroquia de Sahuayo bajo la custodia de su padrino, Rafael Picazo. Su martirio se convirtió en un símbolo de la fe católica y la resistencia Cristera. José Sánchez del Río fue beatificado en Guadalajara el 20 de noviembre de 2005 y canonizado en Roma el 16 de octubre de 2016, siendo reconocido como un santo patrón de la juventud y los Cristeros. Su vida y sacrificio han sido inmortalizados en películas como "Cristiada" y "Mirando al cielo". Este trágico episodio ilustra cómo los conflictos ideológicos nacionales se manifestaron con brutalidad a nivel local, generando profundo sufrimiento y, al mismo tiempo, forjando una identidad religiosa y de resistencia que perdura en la memoria colectiva de Sahuayo.</p>

					<h3>Repunte económico y la obtención del título de ciudad (1952).</h3>

					<p>Tras los turbulentos años de la revolución y la guerra cristera, Sahuayo experimentó un notable repunte económico a partir de 1930. Este resurgimiento económico, impulsado por la estabilidad política post-revolucionaria y las reformas agrarias que redistribuyeron la tierra, sentó las bases para un crecimiento sostenido. Como reconocimiento a su desarrollo económico y urbano, Sahuayo fue elevado al título de "Ciudad" el 28 de noviembre de 1952. Este cambio de estatus no fue meramente nominal; significó la formalización de su creciente importancia como centro urbano y regional. La obtención del título de ciudad marcó una transición de un enfoque predominantemente rural-agrario a una economía más diversificada, con un énfasis creciente en el comercio y la industria, consolidando su posición como un polo de desarrollo en la región de Lerma-Chapala.</p>

					<h3>El Cambio de nombre a Sahuayo de Morelos (1967).</h3>

					<p>El 28 de noviembre de 1967, la cabecera municipal de Sahuayo experimentó un cambio de nombre significativo, pasando de "Sahuayo de Porfirio Díaz" a "Sahuayo de Morelos". Esta modificación fue un acto simbólico de gran calado, que buscaba alinear la identidad de la ciudad con los ideales de la revolución mexicana y distanciarse del legado del porfiriato. Al adoptar el nombre de José María Morelos y Pavón, uno de los héroes más emblemáticos de la Independencia de México, Sahuayo se integró a una narrativa nacionalista que enfatizaba la justicia social y la soberanía popular, en contraposición al régimen autoritario de Porfirio Díaz. Sahuayo, junto con Carácuaro y Nocupétaro, son los únicos municipios en Michoacán dedicados a Morelos. Este cambio de nombre no solo fue una reorientación política y cultural, sino también un refuerzo de una memoria histórica particular, consolidando los valores cívicos asociados a la lucha por la independencia y la revolución.</p>

					<hr>

					<h2>Sahuayo contemporáneo: Identidad, cultura y perspectivas futuras.</h2>

					<p>En la actualidad, Sahuayo de Morelos se define por una identidad rica y multifacética, arraigada en sus tradiciones, su patrimonio y los desafíos de la modernidad.</p>

					<h3>Fiesta, danza y tradiciones.</h3>

					<p>La vida cultural de Sahuayo es vibrante y se manifiesta en diversas festividades que reflejan un profundo sincretismo entre las tradiciones prehispánicas y las creencias católicas. Los Tlahualiles de Sahuayo son una de las tradiciones más prominentes y visualmente impactantes. Cada 25 de julio, se celebra la fiesta en honor al patrono del lugar, Santiago Apóstol, conocida como "El Patrón Santiago". Durante estas celebraciones, los participantes crean máscaras elaboradas, organizan festivales con música y danza, y representan batallas entre los españoles y los pueblos indígenas. Esta representación escenificada del conflicto histórico no es solo un acto festivo, sino una forma en que la comunidad procesa y rememora su pasado, reconociendo tanto la herencia indígena como la imposición colonial. Otra festividad importante es la fiesta de las <i>guares</i> y los <i>guaches</i>, que tiene lugar el 14 de septiembre en celebración al Santo Cristo. Además, durante las festividades de diciembre, se celebran los juegos florales sahuayenses, el máximo reconocimiento a la literatura local, y se otorga el premio Sahuayo de Literatura. La existencia de estas expresiones culturales y literarias demuestra una continuidad en la vida artística e intelectual de la ciudad, consolidando una identidad que valora tanto sus raíces históricas como su producción creativa contemporánea.</p>

					<h3>Patrimonio arquitectónico y personajes ilustres.</h3>

					<p>El patrimonio arquitectónico de Sahuayo de Morelos es un testimonio tangible de su historia y devoción. Entre los monumentos más destacados se encuentran la parroquia de Santiago Apóstol, el templo del sagrado corazón de Jesús, la parroquia de nuestra señora de Guadalupe y el monumento a Cristo Rey. Estas estructuras religiosas no solo son importantes por su valor arquitectónico, sino que también son centros de la vida espiritual y comunitaria.</p>

					<p>La ciudad ha sido cuna y hogar de figuras ilustres que han dejado una huella significativa en diversos campos. Luis Sahagún Cortes, reconocido como un maestro pintor, contribuyó al ámbito artístico. José Sánchez Villaseñor, filósofo y educador, fue el fundador de la Universidad Iberoamericana, destacando en el ámbito académico. El ingeniero José Luis Arregui es recordado como un benefactor del pueblo, responsable de la construcción de la presa para el suministro de agua, la gestión de la introducción del drenaje, la donación de terrenos para la construcción de un edificio para las madres dominicas y el apoyo a los salesianos para establecer la escuela de artes y oficios. Finalmente, José Sánchez del Río, el joven mártir cristero, cuya beatificación y canonización lo han convertido en un símbolo de fe y resistencia, es una figura central en la identidad religiosa de Sahuayo. La presencia de múltiples estructuras religiosas significativas y la veneración de un mártir local, junto con el reconocimiento de intelectuales y filántropos, demuestran que la identidad contemporánea de Sahuayo está profundamente entrelazada con su fe católica, sus contribuciones intelectuales y artísticas, y los esfuerzos de sus ciudadanos por el bienestar comunitario.</p>

					<h3>Desafíos y oportunidades actuales para el municipio.</h3>

					<p>El municipio de Sahuayo de Morelos enfrenta desafíos contemporáneos mientras busca consolidar su desarrollo. El gobierno municipal actual ha manifestado su compromiso de ser inclusivo, centrado en el ser humano y de fomentar la participación ciudadana, promoviendo un sentido de "gran familia llamada Sahuayo". Esta visión apunta a un desarrollo más equitativo y participativo.</p>

					<p>Sin embargo, persisten desafíos significativos, particularmente en relación con las problemáticas que afectan al Lago de Chapala. La región sigue lidiando con problemas como el consumo excesivo de agua, altos niveles de contaminación derivados de descargas industriales y la deficiente gestión de las plantas de tratamiento de aguas residuales, lo que ha llevado a la desaparición y reducción de especies endémicas. Estos problemas ambientales, con raíces históricas en la desecación del lago para beneficio económico de unos pocos, representan una amenaza para la sostenibilidad a largo plazo de la región y el bienestar de sus habitantes. La principal actividad económica del municipio se centra en el comercio y la industria, mientras que las localidades circundantes mantienen una base agrícola. El reto actual para Sahuayo radica en equilibrar su crecimiento económico con la protección ambiental y la promoción de la equidad social. La historia de despojo de tierras y la alteración del ecosistema del lago para el beneficio económico subrayan la necesidad de un enfoque de desarrollo más sostenible y socialmente responsable que aborde las desigualdades históricas y garantice un futuro próspero para todos sus habitantes.</p>

					<hr>

					<p>En resumen, el recorrido histórico de Sahuayo de Morelos revela una comunidad forjada por la interacción de diversas culturas prehispánicas, la imposición y adaptación al sistema colonial, y su participación activa en los grandes movimientos que definieron la nación mexicana. Desde sus orígenes, marcados por la presencia de poblaciones de origen azteca y la posterior hegemonía purépecha, hasta su configuración como municipio independiente y su transformación en ciudad, Sahuayo ha demostrado una notable capacidad de resiliencia y adaptación.</p>

					<p>La conquista española introdujo un sistema de explotación a través de las encomiendas y la expansión ganadera, que llevó al despojo de tierras indígenas y a la consolidación de grandes latifundios como la hacienda de Guaracha. Las crisis demográficas, exacerbadas por epidemias y hambrunas, alteraron profundamente la composición poblacional y social, obligando a la introducción de mano de obra esclava africana.</p>

					<p>El siglo XIX trajo consigo la formalización de Sahuayo como municipio, un paso crucial en su autonomía cívica, y la hacienda de Guaracha experimentó cambios de propiedad que reflejaron las dinámicas de la reforma. El siglo XX fue testigo de la modernización porfiriana, simbolizada por la llegada del ferrocarril, pero también de la acentuación de las desigualdades y la drástica desecación del Lago de Chapala, que benefició a los terratenientes a expensas de los campesinos y el ecosistema.</p>

					<p>La revolución mexicana y la posterior reforma agraria, impulsada por Lázaro Cárdenas, corrigieron en parte las injusticias históricas con la creación del ejido Emiliano Zapata. La guerra cristera, con el martirio de José Sánchez del Río, dejó una profunda huella en la identidad religiosa y de resistencia de la comunidad. El repunte económico de mediados del siglo XX y la obtención del título de ciudad en 1952, seguido por el cambio de nombre a Sahuayo de Morelos en 1967, simbolizan una etapa de consolidación urbana y una reafirmación de su identidad nacionalista.</p>

					<p>La historia de Sahuayo de Morelos es un microcosmos de la historia de México, un relato de adaptación, conflicto y continua redefinición, donde el pasado sigue informando el presente y las perspectivas futuras. En la actualidad, Sahuayo se distingue por su rica vida cultural, sus tradiciones sincréticas y un patrimonio arquitectónico que atestigua su profunda fe.</p>

					<hr>

					<ul>
                  <li>Alvarado, A. (2021, 20 de enero). <i>Lucha Jalisciense</i>. El Ciudadano Jalisco. <a href="https://elciudadanojalisco.mx/lucha-jalisciense/" target="_blank">https://elciudadanojalisco.mx/lucha-jalisciense</a></li>
                  <li>Bastos, S. (2011). La nueva defensa de Mezcala: un proceso de recomunalización a través de la renovación étnica. <i>Relaciones. Estudios de Historia y Sociedad, 32</i>(125), 11-40. <a href="https://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S0185-39292011000100004" target="_blank">https://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S0185-39292011000100004</a></li>
                  <li>Concepto.de. (s.f.). <i>Guerra Cristera - Concepto, historia, causas y consecuencias</i>. <a href="https://concepto.de/guerra-cristera/" target="_blank">https://concepto.de/guerra-cristera</a></li>
                  <li>Corona Páez, M. del C. (2023). La encomienda de Ixmiquilpan: un caso de litigio por la propiedad de la tierra en el siglo XVI. <i>Estudios de Cultura Náhuatl, 65</i>, 120-149. <a href="https://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S1665-899X2023000100120" target="_blank">https://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S1665-899X2023000100120</a></li>
                  <li>Covarrubias, F., Ojeda, A., & Arceo, M. G. (2007). La problemática del lago de Chapala y su cuenca. <i>Quivera, 9</i>(2), 201-218. <a href="https://quivera.uaemex.mx/article/download/10473/8553/" target="_blank">https://quivera.uaemex.mx/article/download/10473/8553</a></li>
                  <li>Crónicas de la Ciénega. (s.f.). <i>Historia regional</i>. <a href="https://cronicasdelacienega.com/tag/historia-regional/" target="_blank">https://cronicasdelacienega.com/tag/historia-regional</a></li>
                  <li>El Sol de Zamora. (s.f.). <i>¿Cuáles son los datos curiosos de Sahuayo y su aniversario?</i> OEM. <a href="https://oem.com.mx/elsoldezamora/turismo/cuales-son-los-datos-curiosos-de-sahuayo-y-su-aniversario-22094017" target="_blank">https://oem.com.mx/elsoldezamora/turismo/cuales-son-los-datos-curiosos-de-sahuayo-y-su-aniversario-22094017</a></li>
                  <li>Gobierno de Jalisco. (s.f.). <i>Historia</i>. <a href="https://www.jalisco.gob.mx/jalisco/historia/" target="_blank">https://www.jalisco.gob.mx/jalisco/historia</a></li>
                  <li>Gobierno Municipal de Sahuayo. (s.f.). <i>Miles de personas participaron en la molienda de la calzada de los mártires cristeros</i>. <a href="http://sahuayomich.gob.mx/new/index.php/noticias/440-miles-de-personas-participaron-en-la-molienda-de-la-calzada-de-los-martires-cristeros" target="_blank">http://sahuayomich.gob.mx/new/index.php/noticias/440-miles-de-personas-participaron-en-la-molienda-de-la-calzada-de-los-martires-cristeros</a></li>
                  <li>Gobierno Municipal de Sahuayo. (s.f.). <i>Realizan las autoridades municipales desfile en honor a Morelos</i>. <a href="http://sahuayomich.gob.mx/new/index.php/noticias/368-realizan-las-autoridades-municipales-desfile-en-honor-a-morelos" target="_blank">http://sahuayomich.gob.mx/new/index.php/noticias/368-realizan-las-autoridades-municipales-desfile-en-honor-a-morelos</a></li>
                  <li>Gobierno Municipal de Sahuayo. (s.f.). <i>Sahuayo</i>. <a href="http://sahuayomich.gob.mx/new/index.php/gobierno/sahuayo" target="_blank">http://sahuayomich.gob.mx/new/index.php/gobierno/sahuayo</a></li>
                  <li>Gobierno Municipal de Sahuayo. (2022, enero). <i>Plan Municipal de Desarrollo Sahuayo 2021-2024</i>. <a href="https://gob.sahuayomich.gob.mx/wp-content/uploads/2022/01/Plan-Municipal-de-Desarrollo-Sahuayo-2021-2024-.pdf" target="_blank">https://gob.sahuayomich.gob.mx/wp-content/uploads/2022/01/Plan-Municipal-de-Desarrollo-Sahuayo-2021-2024-.pdf</a></li>
                  <li>Gobierno Municipal de Sahuayo. (2024, 6 de mayo). <i>Índices</i>. <a href="https://sahuayomich.gob.mx/sisofi/sisofi_2018b/uploads/06-05-2024/INDICES.pdf" target="_blank">https://sahuayomich.gob.mx/sisofi/sisofi_2018b/uploads/06-05-2024/INDICES.pdf</a></li>
                  <li>Gobierno de Sahuayo 2021-2024. (s.f.). <i>Cronología de echos Históricos</i>. <a href="https://gob.sahuayomich.gob.mx/957-2/" target="_blank">https://gob.sahuayomich.gob.mx/957-2</a></li>
                  <li>Gómez de Silva, G. (s.f.). Sahuayo, sahuaya. En <i>Diccionario breve de mexicanismos</i>. Academia Mexicana de la Lengua. <a href="https://www.academia.org.mx/consultas/obras-de-consulta-en-linea/diccionario-breve-de-mexicanismos-de-guido-gomez-de-silva/item/sahuayo-sahuaya" target="_blank">https://www.academia.org.mx/consultas/obras-de-consulta-en-linea/diccionario-breve-de-mexicanismos-de-guido-gomez-de-silva/item/sahuayo-sahuaya</a></li>
                  <li>González Flores, J. G. (2016). La fatídica década de 1780 en una parroquia de Michoacán: epidemias y consecuencias demográficas en Taximaroa, 1780-1790. <i>Relaciones. Estudios de Historia y Sociedad, 37</i>(146), 83-116. <a href="https://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S0185-39292016000200083" target="_blank">https://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S0185-39292016000200083</a></li>
                  <li>Imperio purépecha. (s.f.). In <i>Wikipedia</i>. <a href="https://es.wikipedia.org/wiki/Imperio_pur%C3%A9pecha" target="_blank">https://es.wikipedia.org/wiki/Imperio_purépecha</a></li>
                  <li>Instituto Nacional de los Pueblos Indígenas (INPI). (s.f.). <i>Michoacán</i>. <a href="https://atlas.inpi.gob.mx/michoacan-2/" target="_blank">https://atlas.inpi.gob.mx/michoacan-2</a></li>
                  <li>José Sánchez del Río. (s.f.). In <i>Wikipedia</i>. <a href="https://es.wikipedia.org/wiki/Jos%C3%A9_S%C3%A1nchez_del_R%C3%ADo" target="_blank">https://es.wikipedia.org/wiki/José_Sánchez_del_Río</a></li>
                  <li>Lago de Chapala. (s.f.). In <i>Wikipedia</i>. <a href="https://es.wikipedia.org/wiki/Lago_de_Chapala" target="_blank">https://es.wikipedia.org/wiki/Lago_de_Chapala</a></li>
                  <li>López Alcaraz, H. J. (2024, 12 de junio). <i>El párroco insurgente de Sahuayo</i>. Crónicas de la Ciénega. <a href="https://cronicasdelacienega.com/2024/06/12/el-parroco-insurgente-de-sahuayo/" target="_blank">https://cronicasdelacienega.com/2024/06/12/el-parroco-insurgente-de-sahuayo</a></li>
                  <li>Macías Richard, C. (2008). <i>La Rebelión Delahuertista</i>. Instituto Nacional de Estudios Históricos de las Revoluciones de México. <a href="https://www.inehrm.gob.mx/recursos/Libros/LaRebelionDelahuertista.pdf" target="_blank">https://www.inehrm.gob.mx/recursos/Libros/LaRebelionDelahuertista.pdf</a></li>
                  <li>Mezcala: la isla indómita. (2010). <i>Estudios Jaliscienses, 81</i>, 11-28. <a href="https://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S1607-050X2010000300011" target="_blank">https://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S1607-050X2010000300011</a></li>
                  <li>Michoacán. (s.f.). In <i>Wikipedia</i>. <a href="https://es.wikipedia.org/wiki/Michoac%C3%A1n" target="_blank">https://es.wikipedia.org/wiki/Michoacán</a></li>
                  <li>Miño Grijalva, M. (2004). Los primeros pasos del ganado en México. <i>Relaciones. Estudios de Historia y Sociedad, 25</i>(97), 11-44. <a href="http://sitios.colmich.edu.mx/relaciones25/index.php/numeros-anteriores?id=1119:articulo-59-los-primeros-pasos-del-ganado-en-mexico&catid=11" target="_blank">http://sitios.colmich.edu.mx/relaciones25/index.php/numeros-anteriores?id=1119:articulo-59-los-primeros-pasos-del-ganado-en-mexico&catid=11</a></li>
                  <li>Moreno Toscano, A. (1999, 16 de mayo). <i>¿Qué pasó con el campo mexicano?</i> La Jornada. <a href="https://www.jornada.com.mx/1999/05/16/sig-revision.html" target="_blank">https://www.jornada.com.mx/1999/05/16/sig-revision.html</a></li>
                  <li>Misiones conventuales de Michoacán. (s.f.). In <i>Wikipedia</i>. <a href="https://es.wikipedia.org/wiki/Misiones_conventuales_de_Michoac%C3%A1n" target="_blank">https://es.wikipedia.org/wiki/Misiones_conventuales_de_Michoacán</a></li>
                  <li>Nuño de Guzmán. (s.f.). In <i>Wikipedia</i>. <a href="https://es.wikipedia.org/wiki/Nu%C3%B1o_de_Guzm%C3%A1n" target="_blank">https://es.wikipedia.org/wiki/Nuño_de_Guzmán</a></li>
                  <li>Parroquia de Santiago Apóstol, Sahuayo, Mich. (s.f.). <i>Historia</i>. <a href="https://santiagoapostolsahuayo.es.tl/HISTORIA.htm" target="_blank">https://santiagoapostolsahuayo.es.tl/HISTORIA.htm</a></li>
                  <li>Pueblo coca. (s.f.). In <i>Wikipedia</i>. <a href="https://es.wikipedia.org/wiki/Pueblo_coca" target="_blank">https://es.wikipedia.org/wiki/Pueblo_coca</a></li>
                  <li>Pueblos Originarios. (s.f.). <i>Historia</i>. <a href="http://pueblosoriginarios.com/meso/occidente/purepecha/historia.html" target="_blank">http://pueblosoriginarios.com/meso/occidente/purepecha/historia.html</a></li>
                  <li>Quadratín. (2023, 2 de octubre). <i>Conmemoraron en Sahuayo el natalicio de Morelos</i>. <a href="https://www.quadratin.com.mx/sin-categoria/conmemoraron-en-sahuayo-el-natalicio-de-morelos/" target="_blank">https://www.quadratin.com.mx/sin-categoria/conmemoraron-en-sahuayo-el-natalicio-de-morelos</a></li>
                  <li>Ribera Carbó, A. (2010). Lázaro Cárdenas y los cristeros de Michoacán: Entre la ofensiva militar y la negociación pactada. <i>Historia Mexicana, 60</i>(1), 325-366. <a href="https://historiamexicana.colmex.mx/index.php/RHM/article/download/1319/1181" target="_blank">https://historiamexicana.colmex.mx/index.php/RHM/article/download/1319/1181</a></li>
                  <li>Ribera Carbó, A. (2010). Lázaro Cárdenas y los cristeros de Michoacán. Entre la ofensiva militar y la negociación pactada. <i>Historias, 76</i>, 67-88. <a href="https://revistas.inah.gob.mx/index.php/historias/article/download/18128/19517/39204" target="_blank">https://revistas.inah.gob.mx/index.php/historias/article/download/18128/19517/39204</a></li>
                  <li>Sahuayo. (s.f.). In <i>Wikipedia</i>. <a href="https://en.wikipedia.org/wiki/Sahuayo" target="_blank">https://en.wikipedia.org/wiki/Sahuayo</a></li>
                  <li>Sahuayo de Morelos. (s.f.). In <i>Wikipedia</i>. <a href="https://es.wikipedia.org/wiki/Sahuayo_de_Morelos" target="_blank">https://es.wikipedia.org/wiki/Sahuayo_de_Morelos</a></li>
                  <li>Sánchez Rodríguez, M. (1997). <i>La Hacienda de Guaracha: Adquisición y venta</i>. El Colegio de Michoacán. <a href="https://colmich.repositorioinstitucional.mx/jspui/bitstream/1016/777/1/S%C3%A1nchezRodr%C3%ADguezMart%C3%ADn1997Cap%C3%ADtulo.pdf" target="_blank">https://colmich.repositorioinstitucional.mx</a></li>
                  <li>Sánchez Rodríguez, M. (2004). Identidad social y religión en el Bajío zamorano, 1850-1900: El culto a la Purísima, un mito de fundación. <i>Relaciones. Estudios de Historia y Sociedad, 25</i>(97), 11-44. <a href="http://sitios.colmich.edu.mx/relaciones25/index.php/numeros-anteriores/10-articulos/1485-articulo-27-identidad-social-y-religion-en-el-bajio-zamorano-1850-1900-el-culto-a-la-purisima-un-mito-de-fundacion" target="_blank">http://sitios.colmich.edu.mx/relaciones25/index.php/numeros-anteriores/10-articulos/1485-articulo-27-identidad-social-y-religion-en-el-bajio-zamorano-1850-1900-el-culto-a-la-purisima-un-mito-de-fundacion</a></li>
                  <li>Sánchez Rodríguez, M. (2014). El surgimiento de la ganadería en la Ciénega de Chapala, Michoacán, México: El caso de la Hacienda Guaracha, siglos XVI-XIX. <i>Relaciones. Estudios de Historia y Sociedad, 35</i>(138), 239-270. <a href="https://www.researchgate.net/publication/264052580_El_surgimiento_de_la_ganaderia_en_la_Cienega_de_Chapala_Michoacan_Mexico_El_caso_de_la_Hacienda_Guaracha_siglos_XVI-XIX" target="_blank">https://www.researchgate.net/publication</a></li>
                  <li>Sánchez Rodríguez, M. (2014). La Hacienda de Guaracha: Un caso de estudio de la propiedad rural en Michoacán, 1837-1910. <i>Historia y Sociedad, 26</i>, 100-120. <a href="http://www.scielo.org.co/scielo.php?script=sci_arttext&pid=S2145-132X2014000100006" target="_blank">http://www.scielo.org.co/scielo.php?script=sci_arttext&pid=S2145-132X2014000100006</a></li>
                  <li>Talayera Ibarra, O. U. (2015). La crisis de los años 1785-1786 en Michoacán: ¿el "Gran Hambre" o las grandes epidemias? <i>Tzintzun. Revista de Estudios Históricos, 61</i>, 11-36. <a href="https://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S1870-719X2015000100003" target="_blank">https://www.scielo.org.mx/scielo.php?script=sci_arttext&pid=S1870-719X2015000100003</a></li>
                  <li>Universidad Latina de América (UNLA). (s.f.). <i>La desecación del Lago de Chapala y su impacto en el paisaje y forma de vida</i>. Blog UNLA. <a href="https://www.unla.mx/blogunla/la-desecacion-del-lago-de-chapala-y-su-impacto-en-el-paisaje-y-forma-de-vida" target="_blank">https://www.unla.mx/blogunla/la-desecacion-del-lago-de-chapala-y-su-impacto-en-el-paisaje-y-forma-de-vida</a></li>
                  <li>Uribe Salas, J. A. (2019). El bandolerismo mexicano como respuesta al contexto socioeconómico del Porfiriato: El caso de Michoacán (1876-1911). <i>Perfiles Económicos, 7</i>, 85-112. <a href="https://rcs.uv.cl/index.php/Perfiles/article/download/2617/2545" target="_blank">https://rcs.uv.cl/index.php/Perfiles/article/download/2617/2545</a></li>
                  <li>Von Wobeser, G. (s.f.). El surgimiento de la hacienda en la época colonial. En <i>Historia de las haciendas en México</i>. Universidad Nacional Autónoma de México. <a href="https://historicas.unam.mx/publicaciones/publicadigital/libros/198b/198b_04_03_surgimiento.pdf" target="_blank">https://historicas.unam.mx/publicaciones/publicadigital/libros/198b/198b_04_03_surgimiento.pdf</a></li>
                  <li>Von Wobeser, G. (s.f.). Las estancias de ganado y las labores. En <i>Historia de las haciendas en México</i>. Universidad Nacional Autónoma de México. <a href="https://historicas.unam.mx/publicaciones/publicadigital/libros/198b/198b_04_02_estancias.pdf" target="_blank">https://historicas.unam.mx/publicaciones/publicadigital/libros/198b/198b_04_02_estancias.pdf</a></li>
                  <li>Warren, J. B., & Warren, P. S. (s.f.). <i>La evangelización de Michoacán</i>. Arqueología Mexicana. <a href="https://arqueologiamexicana.mx/mexico-antiguo/la-evangelizacion-de-michoacan" target="_blank">https://arqueologiamexicana.mx/mexico-antiguo/la-evangelizacion-de-michoacan</a></li>
                  <li>YouTube. (s.f.). <i>Historia de la Hacienda de Guaracha, Michoacán</i> [Video]. YouTube. <a href="https://www.youtube.com/watch?v=MX4ne2jSW4s" target="_blank">https://www.youtube.com/watch?v=MX4ne2jSW4s</a></li>
                  <li>YouTube. (s.f.). <i>La nación purépecha: Un pueblo indígena milenario</i> [Video]. YouTube. <a href="https://www.youtube.com/watch?v=DXafrHyLNwY" target="_blank">https://www.youtube.com/watch?v=DXafrHyLNwY</a></li>
               </ul>
					</main>
			</div>
		</div>
<?php
	require_once 'footer.php';
?>