<?php
   $codigosPostales = [
      ['59000', 'Colonia Centro', 'Urbano'],
      ['59000', 'Fraccionamiento José Sánchez del Río', 'Urbano'],
      ['59010', 'Fraccionamiento Alameda', 'Urbano'],
      ['59010', 'Colonia Llanos de Sahuayo', 'Urbano'],
      ['59010', 'Fraccionamiento Jardines de Sahuayo', 'Urbano'],
      ['59010', 'Colonia Las Brisas', 'Urbano'],
      ['59010', 'Colonia Seminario de Oblatos', 'Urbano'],
      ['59010', 'Colonia Arboledas', 'Urbano'],
      ['59012', 'Fraccionamiento Rancho Dorado', 'Urbano'],
      ['59012', 'Fraccionamiento Loma Dorada', 'Urbano'],
      ['59013', 'Fraccionamiento Jardines de San Isidro', 'Urbano'],
      ['59013', 'Fraccionamiento Enrique Prado', 'Urbano'],
      ['59013', 'Fraccionamiento Los Olivos', 'Urbano'],
      ['59013', 'Colonia San Isidro', 'Urbano'],
      ['59014', 'Fraccionamiento Guadalupe', 'Urbano'],
      ['59014', 'Fraccionamiento María Concepción', 'Urbano'],
      ['59014', 'Fraccionamiento San José', 'Urbano'],
      ['59015', 'Fraccionamiento Paso de las Águilas', 'Urbano'],
      ['59020', 'Fraccionamiento INFONAVIT', 'Urbano'],
      ['59020', 'Colonia Dámaso Cárdenas', 'Urbano'],
      ['59020', 'Colonia J. Trinidad Barragán', 'Urbano'],
      ['59020', 'Colonia Marcos Castellanos', 'Urbano'],
      ['59023', 'Colonia Enrique Méndez', 'Urbano'],
      ['59023', 'Colonia Grijalva', 'Urbano'],
      ['59023', 'Colonia La Muda', 'Urbano'],
      ['59026', 'Colonia Royal Country', 'Urbano'],
      ['59026', 'Colonia Niños Héroes', 'Urbano'],
      ['59027', 'Fraccionamiento Los Pinos', 'Urbano'],
      ['59027', 'Fraccionamiento La Aurora', 'Urbano'],
      ['59027', 'Colonia Microindustrial', 'Urbano'],
      ['59027', 'Colonia El Salitre (SARH)', 'Urbano'],
      ['59027', 'Colonia Magisterio', 'Urbano'],
      ['59028', 'Colonia La Popular', 'Urbano'],
      ['59030', 'Fraccionamiento Lindavista', 'Urbano'],
      ['59030', 'Colonia Pedregal de Santiago', 'Urbano'],
      ['59030', 'Colonia Las Rosas', 'Urbano'],
      ['59030', 'Colonia Lindavista', 'Urbano'],
      ['59033', 'Colonia Noria de Montes', 'Urbano'],
      ['59033', 'Colonia Los Sauces', 'Urbano'],
      ['59034', 'Fraccionamiento Pedregal de Santiago', 'Urbano'],
      ['59034', 'Fraccionamiento Bugambilias Residencial', 'Urbano'],
      ['59034', 'Colonia Camino Real', 'Urbano'],
      ['59034', 'Colonia Prados Verdes', 'Urbano'],
      ['59034', 'Fraccionamiento Real Victoria', 'Urbano'],
      ['59035', 'Fraccionamiento Puerta del Sol', 'Urbano'],
      ['59035', 'Fraccionamiento Azaleas I', 'Urbano'],
      ['59035', 'Fraccionamiento Azaleas II', 'Urbano'],
      ['59035', 'Colonia San Onofre', 'Urbano'],
      ['59035', 'Colonia La Yerbabuena', 'Urbano'],
      ['59036', 'Colonia Balcones del Valle', 'Urbano'],
      ['59036', 'Fraccionamiento Cumbres', 'Urbano'],
      ['59036', 'Colonia Peñitas', 'Urbano'],
      ['59040', 'Colonia Cristo Rey', 'Urbano'],
      ['59040', 'Colonia Lomas de Santiago', 'Urbano'],
      ['59040', 'Colonia Colinas del Tepeyac', 'Urbano'],
      ['59043', 'Fraccionamiento Manuel J. Cloutier', 'Urbano'],
      ['59043', 'Colonia Santiaguillo', 'Urbano'],
      ['59044', 'Colonia Lomas de Santiaguito', 'Urbano'],
      ['59044', 'Fraccionamiento Las Barranquillas', 'Urbano'],
      ['59045', 'Fraccionamiento Miradores del Tepeyac', 'Urbano'],
      ['59045', 'Fraccionamiento Jardín Real', 'Urbano'],
      ['59050', 'Fraccionamiento San Rafael', 'Urbano'],
      ['59050', 'Colonia Valle Verde', 'Urbano'],
      ['59050', 'Colonia Forestal', 'Urbano'],
      ['59057', 'Fraccionamiento Roccalta', 'Urbano'],
      ['59057', 'Fraccionamiento Terravida', 'Urbano'],
      ['59057', 'Colonia La Puntita', 'Urbano'],
      ['59057', 'Fraccionamiento Primavera Residencial', 'Urbano'],
      ['59058', 'Fraccionamiento Residencial Sahuayo', 'Urbano'],
      ['59058', 'Fraccionamiento Michoacán', 'Urbano'],
      ['59058', 'Colonia La Limonera', 'Urbano'],
      ['59058', 'Colonia Guadalajara', 'Urbano'],
      ['59100', 'Fraccionamiento Loma Bonita', 'Rural'],
      ['59100', 'Fraccionamiento Lomas del Valle Uno', 'Rural'],
      ['59100', 'Fraccionamiento Campestre la Presa', 'Rural'],
      ['59100', 'Fraccionamiento Bosque de las Lomas', 'Rural'],
      ['59100', 'Fraccionamiento Loma Dorada', 'Rural'],
      ['59100', 'Ranchería Barranca del Aguacate', 'Rural'],
      ['59100', 'Pueblo Rincón de San Andrés', 'Rural'],
      ['59100', 'Colonia Tuna Mansa', 'Rural'],
      ['59100', 'Ranchería La Flor del Agua', 'Rural'],
      ['59100', 'Ranchería Potrero el Molino', 'Rural'],
      ['59100', 'Fraccionamiento Lomas del Valle Dos', 'Rural'],
      ['59100', 'Ranchería La Cabaña', 'Rural'],
      ['59100', 'Ranchería La Calzonuda', 'Rural'],
      ['59100', 'Rancho La Chicharra', 'Rural'],
      ['59102', 'Rancho La Barranca de la Gloria', 'Rural'],
      ['59102', 'Rancho Barranca del Soyate', 'Rural'],
      ['59102', 'Rancho El Añil', 'Rural'],
      ['59102', 'Rancho El Moral', 'Rural'],
      ['59102', 'Rancho La Uva', 'Rural'],
      ['59103', 'Colonia Lomas de la Universidad', 'Rural'],
      ['59104', 'Fraccionamiento Flamingos', 'Urbano'],
      ['59104', 'Fraccionamiento San Miguel', 'Urbano'],
      ['59105', 'Ranchería El Güirio', 'Rural'],
      ['59105', 'Ranchería Las Gallinas', 'Rural'],
      ['59105', 'Rancho La Raya', 'Rural'],
      ['59105', 'Rancho Las Gallinas (La Hacienda)', 'Rural'],
      ['59105', 'Rancho Sin Agua', 'Rural'],
   ];
?>